package com.droiddaemon.libapi.responseModels

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
data class Image(
    @Json(name = "account_id")
    val accountId: Int? = null,
    @Json(name = "account_url")
    val accountUrl: String? = null,
    @Json(name = "ad_config")
    val adConfig: AdConfig? = null,
    @Json(name = "ad_type")
    val adType: Int? = null,
    @Json(name = "ad_url")
    val adUrl: String? = null,
    @Json(name = "animated")
    val animated: Boolean? = null,
    @Json(name = "bandwidth")
    val bandwidth: Long? = null,
    @Json(name = "comment_count")
    val commentCount: Int? = null,
    @Json(name = "cover")
    val cover: String? = null,
    @Json(name = "cover_height")
    val coverHeight: Int? = null,
    @Json(name = "cover_width")
    val coverWidth: Int? = null,
    @Json(name = "datetime")
    val datetime: Int? = null,
    @Json(name = "description")
    val description: Any? = null,
    @Json(name = "downs")
    val downs: Int? = null,
    @Json(name = "edited")
    val edited: Int? = null,
    @Json(name = "favorite")
    val favorite: Boolean? = null,
    @Json(name = "favorite_count")
    val favoriteCount: Int? = null,
    @Json(name = "gifv")
    val gifv: String? = null,
    @Json(name = "has_sound")
    val hasSound: Boolean? = null,
    @Json(name = "height")
    val height: Int? = null,
    @Json(name = "hls")
    val hls: String? = null,
    @Json(name = "id")
    val id: String? = null,
    @Json(name = "images")
    val images: List<Image>? = null,
    @Json(name = "images_count")
    val imagesCount: Int? = null,
    @Json(name = "in_gallery")
    val inGallery: Boolean? = null,
    @Json(name = "in_most_viral")
    val inMostViral: Boolean? = null,
    @Json(name = "include_album_ads")
    val includeAlbumAds: Boolean? = null,
    @Json(name = "is_ad")
    val isAd: Boolean? = null,
    @Json(name = "is_album")
    val isAlbum: Boolean? = null,
    @Json(name = "layout")
    val layout: String? = null,
    @Json(name = "link")
    val link: String? = null,
    @Json(name = "looping")
    val looping: Boolean? = null,
    @Json(name = "mp4")
    val mp4: String? = null,
    @Json(name = "mp4_size")
    val mp4Size: Int? = null,
    @Json(name = "nsfw")
    val nsfw: Boolean? = null,
    @Json(name = "points")
    val points: Int? = null,
    @Json(name = "privacy")
    val privacy: String? = null,
    @Json(name = "processing")
    val processing: Processing? = null,
    @Json(name = "score")
    val score: Int? = null,
    @Json(name = "section")
    val section: String? = null,
    @Json(name = "size")
    val size: Int? = null,
    @Json(name = "tags")
    val tags: List<Tag?>? = null,
    @Json(name = "title")
    val title: String? = null,
    @Json(name = "topic")
    val topic: Any? = null,
    @Json(name = "topic_id")
    val topicId: Any? = null,
    @Json(name = "type")
    val type: String? = null,
    @Json(name = "ups")
    val ups: Int? = null,
    @Json(name = "views")
    val views: Int? = null,
    @Json(name = "vote")
    val vote: Any? = null,
    @Json(name = "width")
    val width: Int? = null
) {
    @JsonClass(generateAdapter = true)
    data class Processing(
        @Json(name = "status")
        val status: String? = null
    )
}